### ISSUE TITLE
[Incompatibility] Riptide not working properly with Localized Weather and Storms Mod With Server Side Rain On

### ISSUE THREAD

**Issue by UberbeastX** [jiGGO1/Trident#2]
When I had the trident mod and had the global overcast on for weather and storms mod to make sure it works with things that need a server side rain state, I'm able to charge up and use riptide but I don't move off of the ground. I just spin in place.

**Comment by jiGGO1** [comment]
I think this is not my problem, but it's clear that the author of Weather 2 will not be fixing bugs for edition 1.12.2. Fortunately, Weather 2 provides an API, so I will try to incorporate it. This way, even during storms, player can use the trident's riptide enchantment. If this does not solve the issue, there is nothing I can do about it.
